CXX = g++
CXX_FLAGS = --std=c++11 -Wall -pedantic

# # Directory-specific rules:
move: move.cpp
	$(CXX) $^ $(CXX_FLAGS) -o $@

# cout2: cout2.cpp
# 	$(LD) $^ $(LDFLAGS) -o $@

# all: cout cout2
# CLEAN_RM += cout cout2
